# Generated by Django 2.2.7 on 2021-02-09 17:33

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False, verbose_name='Archived (Never Delete from AWS)')),
            ],
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived (Do Not Delete from AWS)')),
                ('file', models.FileField(max_length=255, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='')),
                ('glacier_archive_id', models.CharField(blank=True, max_length=500, null=True)),
                ('off_site_backup_date', models.DateTimeField(blank=True, null=True)),
                ('last_seen_date', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s3_backup_tracker.BackupLocation')),
            ],
        ),
    ]
