# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False, verbose_name='Archived (Never Delete from AWS)')),
            ],
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived (Do Not Delete from AWS)')),
                ('filename', models.CharField(max_length=255)),
                ('glacier_archive_id', models.CharField(blank=True, max_length=500, null=True)),
                ('off_site_backup_date', models.DateTimeField(blank=True, null=True)),
                ('last_seen_date', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.BackupLocation')),
            ],
        ),
    ]
